/* automatically generated by rust-bindgen 0.72.1 */

pub type ze_bool_t = u8;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _ze_driver_handle_t {
    _unused: [u8; 0],
}
pub type ze_driver_handle_t = *mut _ze_driver_handle_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _ze_device_handle_t {
    _unused: [u8; 0],
}
pub type ze_device_handle_t = *mut _ze_device_handle_t;
pub const ZE_RESULT_SUCCESS: _ze_result_t = 0;
pub const ZE_RESULT_NOT_READY: _ze_result_t = 1;
pub const ZE_RESULT_ERROR_DEVICE_LOST: _ze_result_t = 1879048193;
pub const ZE_RESULT_ERROR_OUT_OF_HOST_MEMORY: _ze_result_t = 1879048194;
pub const ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY: _ze_result_t = 1879048195;
pub const ZE_RESULT_ERROR_MODULE_BUILD_FAILURE: _ze_result_t = 1879048196;
pub const ZE_RESULT_ERROR_MODULE_LINK_FAILURE: _ze_result_t = 1879048197;
pub const ZE_RESULT_ERROR_DEVICE_REQUIRES_RESET: _ze_result_t = 1879048198;
pub const ZE_RESULT_ERROR_DEVICE_IN_LOW_POWER_STATE: _ze_result_t = 1879048199;
pub const ZE_RESULT_EXP_ERROR_DEVICE_IS_NOT_VERTEX: _ze_result_t = 2146435073;
pub const ZE_RESULT_EXP_ERROR_VERTEX_IS_NOT_DEVICE: _ze_result_t = 2146435074;
pub const ZE_RESULT_EXP_ERROR_REMOTE_DEVICE: _ze_result_t = 2146435075;
pub const ZE_RESULT_EXP_ERROR_OPERANDS_INCOMPATIBLE: _ze_result_t = 2146435076;
pub const ZE_RESULT_EXP_RTAS_BUILD_RETRY: _ze_result_t = 2146435077;
pub const ZE_RESULT_EXP_RTAS_BUILD_DEFERRED: _ze_result_t = 2146435078;
pub const ZE_RESULT_ERROR_INSUFFICIENT_PERMISSIONS: _ze_result_t = 1879113728;
pub const ZE_RESULT_ERROR_NOT_AVAILABLE: _ze_result_t = 1879113729;
pub const ZE_RESULT_ERROR_DEPENDENCY_UNAVAILABLE: _ze_result_t = 1879179264;
pub const ZE_RESULT_WARNING_DROPPED_DATA: _ze_result_t = 1879179265;
pub const ZE_RESULT_ERROR_UNINITIALIZED: _ze_result_t = 2013265921;
pub const ZE_RESULT_ERROR_UNSUPPORTED_VERSION: _ze_result_t = 2013265922;
pub const ZE_RESULT_ERROR_UNSUPPORTED_FEATURE: _ze_result_t = 2013265923;
pub const ZE_RESULT_ERROR_INVALID_ARGUMENT: _ze_result_t = 2013265924;
pub const ZE_RESULT_ERROR_INVALID_NULL_HANDLE: _ze_result_t = 2013265925;
pub const ZE_RESULT_ERROR_HANDLE_OBJECT_IN_USE: _ze_result_t = 2013265926;
pub const ZE_RESULT_ERROR_INVALID_NULL_POINTER: _ze_result_t = 2013265927;
pub const ZE_RESULT_ERROR_INVALID_SIZE: _ze_result_t = 2013265928;
pub const ZE_RESULT_ERROR_UNSUPPORTED_SIZE: _ze_result_t = 2013265929;
pub const ZE_RESULT_ERROR_UNSUPPORTED_ALIGNMENT: _ze_result_t = 2013265930;
pub const ZE_RESULT_ERROR_INVALID_SYNCHRONIZATION_OBJECT: _ze_result_t = 2013265931;
pub const ZE_RESULT_ERROR_INVALID_ENUMERATION: _ze_result_t = 2013265932;
pub const ZE_RESULT_ERROR_UNSUPPORTED_ENUMERATION: _ze_result_t = 2013265933;
pub const ZE_RESULT_ERROR_UNSUPPORTED_IMAGE_FORMAT: _ze_result_t = 2013265934;
pub const ZE_RESULT_ERROR_INVALID_NATIVE_BINARY: _ze_result_t = 2013265935;
pub const ZE_RESULT_ERROR_INVALID_GLOBAL_NAME: _ze_result_t = 2013265936;
pub const ZE_RESULT_ERROR_INVALID_KERNEL_NAME: _ze_result_t = 2013265937;
pub const ZE_RESULT_ERROR_INVALID_FUNCTION_NAME: _ze_result_t = 2013265938;
pub const ZE_RESULT_ERROR_INVALID_GROUP_SIZE_DIMENSION: _ze_result_t = 2013265939;
pub const ZE_RESULT_ERROR_INVALID_GLOBAL_WIDTH_DIMENSION: _ze_result_t = 2013265940;
pub const ZE_RESULT_ERROR_INVALID_KERNEL_ARGUMENT_INDEX: _ze_result_t = 2013265941;
pub const ZE_RESULT_ERROR_INVALID_KERNEL_ARGUMENT_SIZE: _ze_result_t = 2013265942;
pub const ZE_RESULT_ERROR_INVALID_KERNEL_ATTRIBUTE_VALUE: _ze_result_t = 2013265943;
pub const ZE_RESULT_ERROR_INVALID_MODULE_UNLINKED: _ze_result_t = 2013265944;
pub const ZE_RESULT_ERROR_INVALID_COMMAND_LIST_TYPE: _ze_result_t = 2013265945;
pub const ZE_RESULT_ERROR_OVERLAPPING_REGIONS: _ze_result_t = 2013265946;
pub const ZE_RESULT_WARNING_ACTION_REQUIRED: _ze_result_t = 2013265947;
pub const ZE_RESULT_ERROR_INVALID_KERNEL_HANDLE: _ze_result_t = 2013265948;
pub const ZE_RESULT_EXT_RTAS_BUILD_RETRY: _ze_result_t = 2013265949;
pub const ZE_RESULT_EXT_RTAS_BUILD_DEFERRED: _ze_result_t = 2013265950;
pub const ZE_RESULT_EXT_ERROR_OPERANDS_INCOMPATIBLE: _ze_result_t = 2013265951;
pub const ZE_RESULT_ERROR_SURVIVABILITY_MODE_DETECTED: _ze_result_t = 2013265952;
pub const ZE_RESULT_ERROR_ADDRESS_NOT_FOUND: _ze_result_t = 2013265953;
pub const ZE_RESULT_ERROR_UNKNOWN: _ze_result_t = 2147483646;
pub const ZE_RESULT_FORCE_UINT32: _ze_result_t = 2147483647;
pub type _ze_result_t = ::std::os::raw::c_uint;
pub use self::_ze_result_t as ze_result_t;
pub const ZE_STRUCTURE_TYPE_DRIVER_PROPERTIES: _ze_structure_type_t = 1;
pub const ZE_STRUCTURE_TYPE_DRIVER_IPC_PROPERTIES: _ze_structure_type_t = 2;
pub const ZE_STRUCTURE_TYPE_DEVICE_PROPERTIES: _ze_structure_type_t = 3;
pub const ZE_STRUCTURE_TYPE_DEVICE_COMPUTE_PROPERTIES: _ze_structure_type_t = 4;
pub const ZE_STRUCTURE_TYPE_DEVICE_MODULE_PROPERTIES: _ze_structure_type_t = 5;
pub const ZE_STRUCTURE_TYPE_COMMAND_QUEUE_GROUP_PROPERTIES: _ze_structure_type_t = 6;
pub const ZE_STRUCTURE_TYPE_DEVICE_MEMORY_PROPERTIES: _ze_structure_type_t = 7;
pub const ZE_STRUCTURE_TYPE_DEVICE_MEMORY_ACCESS_PROPERTIES: _ze_structure_type_t = 8;
pub const ZE_STRUCTURE_TYPE_DEVICE_CACHE_PROPERTIES: _ze_structure_type_t = 9;
pub const ZE_STRUCTURE_TYPE_DEVICE_IMAGE_PROPERTIES: _ze_structure_type_t = 10;
pub const ZE_STRUCTURE_TYPE_DEVICE_P2P_PROPERTIES: _ze_structure_type_t = 11;
pub const ZE_STRUCTURE_TYPE_DEVICE_EXTERNAL_MEMORY_PROPERTIES: _ze_structure_type_t = 12;
pub const ZE_STRUCTURE_TYPE_CONTEXT_DESC: _ze_structure_type_t = 13;
pub const ZE_STRUCTURE_TYPE_COMMAND_QUEUE_DESC: _ze_structure_type_t = 14;
pub const ZE_STRUCTURE_TYPE_COMMAND_LIST_DESC: _ze_structure_type_t = 15;
pub const ZE_STRUCTURE_TYPE_EVENT_POOL_DESC: _ze_structure_type_t = 16;
pub const ZE_STRUCTURE_TYPE_EVENT_DESC: _ze_structure_type_t = 17;
pub const ZE_STRUCTURE_TYPE_FENCE_DESC: _ze_structure_type_t = 18;
pub const ZE_STRUCTURE_TYPE_IMAGE_DESC: _ze_structure_type_t = 19;
pub const ZE_STRUCTURE_TYPE_IMAGE_PROPERTIES: _ze_structure_type_t = 20;
pub const ZE_STRUCTURE_TYPE_DEVICE_MEM_ALLOC_DESC: _ze_structure_type_t = 21;
pub const ZE_STRUCTURE_TYPE_HOST_MEM_ALLOC_DESC: _ze_structure_type_t = 22;
pub const ZE_STRUCTURE_TYPE_MEMORY_ALLOCATION_PROPERTIES: _ze_structure_type_t = 23;
pub const ZE_STRUCTURE_TYPE_EXTERNAL_MEMORY_EXPORT_DESC: _ze_structure_type_t = 24;
pub const ZE_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMPORT_FD: _ze_structure_type_t = 25;
pub const ZE_STRUCTURE_TYPE_EXTERNAL_MEMORY_EXPORT_FD: _ze_structure_type_t = 26;
pub const ZE_STRUCTURE_TYPE_MODULE_DESC: _ze_structure_type_t = 27;
pub const ZE_STRUCTURE_TYPE_MODULE_PROPERTIES: _ze_structure_type_t = 28;
pub const ZE_STRUCTURE_TYPE_KERNEL_DESC: _ze_structure_type_t = 29;
pub const ZE_STRUCTURE_TYPE_KERNEL_PROPERTIES: _ze_structure_type_t = 30;
pub const ZE_STRUCTURE_TYPE_SAMPLER_DESC: _ze_structure_type_t = 31;
pub const ZE_STRUCTURE_TYPE_PHYSICAL_MEM_DESC: _ze_structure_type_t = 32;
pub const ZE_STRUCTURE_TYPE_KERNEL_PREFERRED_GROUP_SIZE_PROPERTIES: _ze_structure_type_t = 33;
pub const ZE_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMPORT_WIN32: _ze_structure_type_t = 34;
pub const ZE_STRUCTURE_TYPE_EXTERNAL_MEMORY_EXPORT_WIN32: _ze_structure_type_t = 35;
pub const ZE_STRUCTURE_TYPE_DEVICE_RAYTRACING_EXT_PROPERTIES: _ze_structure_type_t = 65537;
pub const ZE_STRUCTURE_TYPE_RAYTRACING_MEM_ALLOC_EXT_DESC: _ze_structure_type_t = 65538;
pub const ZE_STRUCTURE_TYPE_FLOAT_ATOMIC_EXT_PROPERTIES: _ze_structure_type_t = 65539;
pub const ZE_STRUCTURE_TYPE_CACHE_RESERVATION_EXT_DESC: _ze_structure_type_t = 65540;
pub const ZE_STRUCTURE_TYPE_EU_COUNT_EXT: _ze_structure_type_t = 65541;
pub const ZE_STRUCTURE_TYPE_SRGB_EXT_DESC: _ze_structure_type_t = 65542;
pub const ZE_STRUCTURE_TYPE_LINKAGE_INSPECTION_EXT_DESC: _ze_structure_type_t = 65543;
pub const ZE_STRUCTURE_TYPE_PCI_EXT_PROPERTIES: _ze_structure_type_t = 65544;
pub const ZE_STRUCTURE_TYPE_DRIVER_MEMORY_FREE_EXT_PROPERTIES: _ze_structure_type_t = 65545;
pub const ZE_STRUCTURE_TYPE_MEMORY_FREE_EXT_DESC: _ze_structure_type_t = 65546;
pub const ZE_STRUCTURE_TYPE_MEMORY_COMPRESSION_HINTS_EXT_DESC: _ze_structure_type_t = 65547;
pub const ZE_STRUCTURE_TYPE_IMAGE_ALLOCATION_EXT_PROPERTIES: _ze_structure_type_t = 65548;
pub const ZE_STRUCTURE_TYPE_DEVICE_LUID_EXT_PROPERTIES: _ze_structure_type_t = 65549;
pub const ZE_STRUCTURE_TYPE_DEVICE_MEMORY_EXT_PROPERTIES: _ze_structure_type_t = 65550;
pub const ZE_STRUCTURE_TYPE_DEVICE_IP_VERSION_EXT: _ze_structure_type_t = 65551;
pub const ZE_STRUCTURE_TYPE_IMAGE_VIEW_PLANAR_EXT_DESC: _ze_structure_type_t = 65552;
pub const ZE_STRUCTURE_TYPE_EVENT_QUERY_KERNEL_TIMESTAMPS_EXT_PROPERTIES: _ze_structure_type_t =
    65553;
pub const ZE_STRUCTURE_TYPE_EVENT_QUERY_KERNEL_TIMESTAMPS_RESULTS_EXT_PROPERTIES:
    _ze_structure_type_t = 65554;
pub const ZE_STRUCTURE_TYPE_KERNEL_MAX_GROUP_SIZE_EXT_PROPERTIES: _ze_structure_type_t = 65555;
pub const ZE_STRUCTURE_TYPE_IMAGE_FORMAT_SUPPORT_EXT_PROPERTIES: _ze_structure_type_t = 65556;
pub const ZE_STRUCTURE_TYPE_RELAXED_ALLOCATION_LIMITS_EXP_DESC: _ze_structure_type_t = 131073;
pub const ZE_STRUCTURE_TYPE_MODULE_PROGRAM_EXP_DESC: _ze_structure_type_t = 131074;
pub const ZE_STRUCTURE_TYPE_SCHEDULING_HINT_EXP_PROPERTIES: _ze_structure_type_t = 131075;
pub const ZE_STRUCTURE_TYPE_SCHEDULING_HINT_EXP_DESC: _ze_structure_type_t = 131076;
pub const ZE_STRUCTURE_TYPE_IMAGE_VIEW_PLANAR_EXP_DESC: _ze_structure_type_t = 131077;
pub const ZE_STRUCTURE_TYPE_DEVICE_PROPERTIES_1_2: _ze_structure_type_t = 131078;
pub const ZE_STRUCTURE_TYPE_IMAGE_MEMORY_EXP_PROPERTIES: _ze_structure_type_t = 131079;
pub const ZE_STRUCTURE_TYPE_POWER_SAVING_HINT_EXP_DESC: _ze_structure_type_t = 131080;
pub const ZE_STRUCTURE_TYPE_COPY_BANDWIDTH_EXP_PROPERTIES: _ze_structure_type_t = 131081;
pub const ZE_STRUCTURE_TYPE_DEVICE_P2P_BANDWIDTH_EXP_PROPERTIES: _ze_structure_type_t = 131082;
pub const ZE_STRUCTURE_TYPE_FABRIC_VERTEX_EXP_PROPERTIES: _ze_structure_type_t = 131083;
pub const ZE_STRUCTURE_TYPE_FABRIC_EDGE_EXP_PROPERTIES: _ze_structure_type_t = 131084;
pub const ZE_STRUCTURE_TYPE_MEMORY_SUB_ALLOCATIONS_EXP_PROPERTIES: _ze_structure_type_t = 131085;
pub const ZE_STRUCTURE_TYPE_RTAS_BUILDER_EXP_DESC: _ze_structure_type_t = 131086;
pub const ZE_STRUCTURE_TYPE_RTAS_BUILDER_BUILD_OP_EXP_DESC: _ze_structure_type_t = 131087;
pub const ZE_STRUCTURE_TYPE_RTAS_BUILDER_EXP_PROPERTIES: _ze_structure_type_t = 131088;
pub const ZE_STRUCTURE_TYPE_RTAS_PARALLEL_OPERATION_EXP_PROPERTIES: _ze_structure_type_t = 131089;
pub const ZE_STRUCTURE_TYPE_RTAS_DEVICE_EXP_PROPERTIES: _ze_structure_type_t = 131090;
pub const ZE_STRUCTURE_TYPE_RTAS_GEOMETRY_AABBS_EXP_CB_PARAMS: _ze_structure_type_t = 131091;
pub const ZE_STRUCTURE_TYPE_COUNTER_BASED_EVENT_POOL_EXP_DESC: _ze_structure_type_t = 131092;
pub const ZE_STRUCTURE_TYPE_MUTABLE_COMMAND_LIST_EXP_PROPERTIES: _ze_structure_type_t = 131093;
pub const ZE_STRUCTURE_TYPE_MUTABLE_COMMAND_LIST_EXP_DESC: _ze_structure_type_t = 131094;
pub const ZE_STRUCTURE_TYPE_MUTABLE_COMMAND_ID_EXP_DESC: _ze_structure_type_t = 131095;
pub const ZE_STRUCTURE_TYPE_MUTABLE_COMMANDS_EXP_DESC: _ze_structure_type_t = 131096;
pub const ZE_STRUCTURE_TYPE_MUTABLE_KERNEL_ARGUMENT_EXP_DESC: _ze_structure_type_t = 131097;
pub const ZE_STRUCTURE_TYPE_MUTABLE_GROUP_COUNT_EXP_DESC: _ze_structure_type_t = 131098;
pub const ZE_STRUCTURE_TYPE_MUTABLE_GROUP_SIZE_EXP_DESC: _ze_structure_type_t = 131099;
pub const ZE_STRUCTURE_TYPE_MUTABLE_GLOBAL_OFFSET_EXP_DESC: _ze_structure_type_t = 131100;
pub const ZE_STRUCTURE_TYPE_PITCHED_ALLOC_DEVICE_EXP_PROPERTIES: _ze_structure_type_t = 131101;
pub const ZE_STRUCTURE_TYPE_BINDLESS_IMAGE_EXP_DESC: _ze_structure_type_t = 131102;
pub const ZE_STRUCTURE_TYPE_PITCHED_IMAGE_EXP_DESC: _ze_structure_type_t = 131103;
pub const ZE_STRUCTURE_TYPE_MUTABLE_GRAPH_ARGUMENT_EXP_DESC: _ze_structure_type_t = 131104;
pub const ZE_STRUCTURE_TYPE_INIT_DRIVER_TYPE_DESC: _ze_structure_type_t = 131105;
pub const ZE_STRUCTURE_TYPE_EXTERNAL_SEMAPHORE_EXT_DESC: _ze_structure_type_t = 131106;
pub const ZE_STRUCTURE_TYPE_EXTERNAL_SEMAPHORE_WIN32_EXT_DESC: _ze_structure_type_t = 131107;
pub const ZE_STRUCTURE_TYPE_EXTERNAL_SEMAPHORE_FD_EXT_DESC: _ze_structure_type_t = 131108;
pub const ZE_STRUCTURE_TYPE_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_EXT: _ze_structure_type_t = 131109;
pub const ZE_STRUCTURE_TYPE_EXTERNAL_SEMAPHORE_WAIT_PARAMS_EXT: _ze_structure_type_t = 131110;
pub const ZE_STRUCTURE_TYPE_DRIVER_DDI_HANDLES_EXT_PROPERTIES: _ze_structure_type_t = 131111;
pub const ZE_STRUCTURE_TYPE_DEVICE_CACHELINE_SIZE_EXT: _ze_structure_type_t = 131112;
pub const ZE_STRUCTURE_TYPE_DEVICE_VECTOR_WIDTH_PROPERTIES_EXT: _ze_structure_type_t = 131113;
pub const ZE_STRUCTURE_TYPE_RTAS_BUILDER_EXT_DESC: _ze_structure_type_t = 131120;
pub const ZE_STRUCTURE_TYPE_RTAS_BUILDER_BUILD_OP_EXT_DESC: _ze_structure_type_t = 131121;
pub const ZE_STRUCTURE_TYPE_RTAS_BUILDER_EXT_PROPERTIES: _ze_structure_type_t = 131122;
pub const ZE_STRUCTURE_TYPE_RTAS_PARALLEL_OPERATION_EXT_PROPERTIES: _ze_structure_type_t = 131123;
pub const ZE_STRUCTURE_TYPE_RTAS_DEVICE_EXT_PROPERTIES: _ze_structure_type_t = 131124;
pub const ZE_STRUCTURE_TYPE_RTAS_GEOMETRY_AABBS_EXT_CB_PARAMS: _ze_structure_type_t = 131125;
pub const ZE_STRUCTURE_TYPE_COMMAND_LIST_APPEND_PARAM_COOPERATIVE_DESC: _ze_structure_type_t =
    131126;
pub const ZE_STRUCTURE_TYPE_EXTERNAL_MEMMAP_SYSMEM_EXT_DESC: _ze_structure_type_t = 131127;
pub const ZE_STRUCTURE_TYPE_PITCHED_ALLOC_2DIMAGE_LINEAR_PITCH_EXP_INFO: _ze_structure_type_t =
    131128;
pub const ZE_STRUCTURE_TYPE_KERNEL_ALLOCATION_PROPERTIES: _ze_structure_type_t = 131129;
pub const ZE_STRUCTURE_TYPE_EVENT_COUNTER_BASED_DESC: _ze_structure_type_t = 131130;
pub const ZE_STRUCTURE_TYPE_EVENT_COUNTER_BASED_EXTERNAL_SYNC_ALLOCATION_DESC:
    _ze_structure_type_t = 131131;
pub const ZE_STRUCTURE_TYPE_EVENT_SYNC_MODE_DESC: _ze_structure_type_t = 131132;
pub const ZE_STRUCTURE_TYPE_IPC_MEM_HANDLE_TYPE_EXT_DESC: _ze_structure_type_t = 131133;
pub const ZE_STRUCTURE_TYPE_DEVICE_EVENT_PROPERTIES: _ze_structure_type_t = 131134;
pub const ZE_STRUCTURE_TYPE_EVENT_COUNTER_BASED_EXTERNAL_AGGREGATE_STORAGE_DESC:
    _ze_structure_type_t = 131135;
pub const ZE_STRUCTURE_TYPE_PHYSICAL_MEM_PROPERTIES: _ze_structure_type_t = 131136;
pub const ZE_STRUCTURE_TYPE_DEVICE_USABLEMEM_SIZE_EXT_PROPERTIES: _ze_structure_type_t = 131137;
pub const ZE_STRUCTURE_TYPE_CUSTOM_PITCH_EXP_DESC: _ze_structure_type_t = 131138;
pub const ZE_STRUCTURE_TYPE_FORCE_UINT32: _ze_structure_type_t = 2147483647;
pub type _ze_structure_type_t = ::std::os::raw::c_uint;
pub use self::_ze_structure_type_t as ze_structure_type_t;
pub type ze_device_uuid_t = _ze_device_uuid_t;
pub type ze_device_properties_t = _ze_device_properties_t;
pub const ZE_DEVICE_TYPE_GPU: _ze_device_type_t = 1;
pub const ZE_DEVICE_TYPE_CPU: _ze_device_type_t = 2;
pub const ZE_DEVICE_TYPE_FPGA: _ze_device_type_t = 3;
pub const ZE_DEVICE_TYPE_MCA: _ze_device_type_t = 4;
pub const ZE_DEVICE_TYPE_VPU: _ze_device_type_t = 5;
pub const ZE_DEVICE_TYPE_FORCE_UINT32: _ze_device_type_t = 2147483647;
pub type _ze_device_type_t = ::std::os::raw::c_uint;
pub use self::_ze_device_type_t as ze_device_type_t;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _ze_device_uuid_t {
    pub id: [u8; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _ze_device_uuid_t"][::std::mem::size_of::<_ze_device_uuid_t>() - 16usize];
    ["Alignment of _ze_device_uuid_t"][::std::mem::align_of::<_ze_device_uuid_t>() - 1usize];
    ["Offset of field: _ze_device_uuid_t::id"]
        [::std::mem::offset_of!(_ze_device_uuid_t, id) - 0usize];
};
pub type ze_device_property_flags_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _ze_device_properties_t {
    pub stype: ze_structure_type_t,
    pub pNext: *mut ::std::os::raw::c_void,
    pub type_: ze_device_type_t,
    pub vendorId: u32,
    pub deviceId: u32,
    pub flags: ze_device_property_flags_t,
    pub subdeviceId: u32,
    pub coreClockRate: u32,
    pub maxMemAllocSize: u64,
    pub maxHardwareContexts: u32,
    pub maxCommandQueuePriority: u32,
    pub numThreadsPerEU: u32,
    pub physicalEUSimdWidth: u32,
    pub numEUsPerSubslice: u32,
    pub numSubslicesPerSlice: u32,
    pub numSlices: u32,
    pub timerResolution: u64,
    pub timestampValidBits: u32,
    pub kernelTimestampValidBits: u32,
    pub uuid: ze_device_uuid_t,
    pub name: [::std::os::raw::c_char; 256usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _ze_device_properties_t"]
        [::std::mem::size_of::<_ze_device_properties_t>() - 368usize];
    ["Alignment of _ze_device_properties_t"]
        [::std::mem::align_of::<_ze_device_properties_t>() - 8usize];
    ["Offset of field: _ze_device_properties_t::stype"]
        [::std::mem::offset_of!(_ze_device_properties_t, stype) - 0usize];
    ["Offset of field: _ze_device_properties_t::pNext"]
        [::std::mem::offset_of!(_ze_device_properties_t, pNext) - 8usize];
    ["Offset of field: _ze_device_properties_t::type_"]
        [::std::mem::offset_of!(_ze_device_properties_t, type_) - 16usize];
    ["Offset of field: _ze_device_properties_t::vendorId"]
        [::std::mem::offset_of!(_ze_device_properties_t, vendorId) - 20usize];
    ["Offset of field: _ze_device_properties_t::deviceId"]
        [::std::mem::offset_of!(_ze_device_properties_t, deviceId) - 24usize];
    ["Offset of field: _ze_device_properties_t::flags"]
        [::std::mem::offset_of!(_ze_device_properties_t, flags) - 28usize];
    ["Offset of field: _ze_device_properties_t::subdeviceId"]
        [::std::mem::offset_of!(_ze_device_properties_t, subdeviceId) - 32usize];
    ["Offset of field: _ze_device_properties_t::coreClockRate"]
        [::std::mem::offset_of!(_ze_device_properties_t, coreClockRate) - 36usize];
    ["Offset of field: _ze_device_properties_t::maxMemAllocSize"]
        [::std::mem::offset_of!(_ze_device_properties_t, maxMemAllocSize) - 40usize];
    ["Offset of field: _ze_device_properties_t::maxHardwareContexts"]
        [::std::mem::offset_of!(_ze_device_properties_t, maxHardwareContexts) - 48usize];
    ["Offset of field: _ze_device_properties_t::maxCommandQueuePriority"]
        [::std::mem::offset_of!(_ze_device_properties_t, maxCommandQueuePriority) - 52usize];
    ["Offset of field: _ze_device_properties_t::numThreadsPerEU"]
        [::std::mem::offset_of!(_ze_device_properties_t, numThreadsPerEU) - 56usize];
    ["Offset of field: _ze_device_properties_t::physicalEUSimdWidth"]
        [::std::mem::offset_of!(_ze_device_properties_t, physicalEUSimdWidth) - 60usize];
    ["Offset of field: _ze_device_properties_t::numEUsPerSubslice"]
        [::std::mem::offset_of!(_ze_device_properties_t, numEUsPerSubslice) - 64usize];
    ["Offset of field: _ze_device_properties_t::numSubslicesPerSlice"]
        [::std::mem::offset_of!(_ze_device_properties_t, numSubslicesPerSlice) - 68usize];
    ["Offset of field: _ze_device_properties_t::numSlices"]
        [::std::mem::offset_of!(_ze_device_properties_t, numSlices) - 72usize];
    ["Offset of field: _ze_device_properties_t::timerResolution"]
        [::std::mem::offset_of!(_ze_device_properties_t, timerResolution) - 80usize];
    ["Offset of field: _ze_device_properties_t::timestampValidBits"]
        [::std::mem::offset_of!(_ze_device_properties_t, timestampValidBits) - 88usize];
    ["Offset of field: _ze_device_properties_t::kernelTimestampValidBits"]
        [::std::mem::offset_of!(_ze_device_properties_t, kernelTimestampValidBits) - 92usize];
    ["Offset of field: _ze_device_properties_t::uuid"]
        [::std::mem::offset_of!(_ze_device_properties_t, uuid) - 96usize];
    ["Offset of field: _ze_device_properties_t::name"]
        [::std::mem::offset_of!(_ze_device_properties_t, name) - 112usize];
};
impl Default for _ze_device_properties_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type zes_driver_handle_t = ze_driver_handle_t;
pub type zes_device_handle_t = ze_device_handle_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _zes_pwr_handle_t {
    _unused: [u8; 0],
}
pub type zes_pwr_handle_t = *mut _zes_pwr_handle_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _zes_freq_handle_t {
    _unused: [u8; 0],
}
pub type zes_freq_handle_t = *mut _zes_freq_handle_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _zes_engine_handle_t {
    _unused: [u8; 0],
}
pub type zes_engine_handle_t = *mut _zes_engine_handle_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _zes_temp_handle_t {
    _unused: [u8; 0],
}
pub type zes_temp_handle_t = *mut _zes_temp_handle_t;
pub const ZES_STRUCTURE_TYPE_DEVICE_PROPERTIES: _zes_structure_type_t = 1;
pub const ZES_STRUCTURE_TYPE_PCI_PROPERTIES: _zes_structure_type_t = 2;
pub const ZES_STRUCTURE_TYPE_PCI_BAR_PROPERTIES: _zes_structure_type_t = 3;
pub const ZES_STRUCTURE_TYPE_DIAG_PROPERTIES: _zes_structure_type_t = 4;
pub const ZES_STRUCTURE_TYPE_ENGINE_PROPERTIES: _zes_structure_type_t = 5;
pub const ZES_STRUCTURE_TYPE_FABRIC_PORT_PROPERTIES: _zes_structure_type_t = 6;
pub const ZES_STRUCTURE_TYPE_FAN_PROPERTIES: _zes_structure_type_t = 7;
pub const ZES_STRUCTURE_TYPE_FIRMWARE_PROPERTIES: _zes_structure_type_t = 8;
pub const ZES_STRUCTURE_TYPE_FREQ_PROPERTIES: _zes_structure_type_t = 9;
pub const ZES_STRUCTURE_TYPE_LED_PROPERTIES: _zes_structure_type_t = 10;
pub const ZES_STRUCTURE_TYPE_MEM_PROPERTIES: _zes_structure_type_t = 11;
pub const ZES_STRUCTURE_TYPE_PERF_PROPERTIES: _zes_structure_type_t = 12;
pub const ZES_STRUCTURE_TYPE_POWER_PROPERTIES: _zes_structure_type_t = 13;
pub const ZES_STRUCTURE_TYPE_PSU_PROPERTIES: _zes_structure_type_t = 14;
pub const ZES_STRUCTURE_TYPE_RAS_PROPERTIES: _zes_structure_type_t = 15;
pub const ZES_STRUCTURE_TYPE_SCHED_PROPERTIES: _zes_structure_type_t = 16;
pub const ZES_STRUCTURE_TYPE_SCHED_TIMEOUT_PROPERTIES: _zes_structure_type_t = 17;
pub const ZES_STRUCTURE_TYPE_SCHED_TIMESLICE_PROPERTIES: _zes_structure_type_t = 18;
pub const ZES_STRUCTURE_TYPE_STANDBY_PROPERTIES: _zes_structure_type_t = 19;
pub const ZES_STRUCTURE_TYPE_TEMP_PROPERTIES: _zes_structure_type_t = 20;
pub const ZES_STRUCTURE_TYPE_DEVICE_STATE: _zes_structure_type_t = 21;
pub const ZES_STRUCTURE_TYPE_PROCESS_STATE: _zes_structure_type_t = 22;
pub const ZES_STRUCTURE_TYPE_PCI_STATE: _zes_structure_type_t = 23;
pub const ZES_STRUCTURE_TYPE_FABRIC_PORT_CONFIG: _zes_structure_type_t = 24;
pub const ZES_STRUCTURE_TYPE_FABRIC_PORT_STATE: _zes_structure_type_t = 25;
pub const ZES_STRUCTURE_TYPE_FAN_CONFIG: _zes_structure_type_t = 26;
pub const ZES_STRUCTURE_TYPE_FREQ_STATE: _zes_structure_type_t = 27;
pub const ZES_STRUCTURE_TYPE_OC_CAPABILITIES: _zes_structure_type_t = 28;
pub const ZES_STRUCTURE_TYPE_LED_STATE: _zes_structure_type_t = 29;
pub const ZES_STRUCTURE_TYPE_MEM_STATE: _zes_structure_type_t = 30;
pub const ZES_STRUCTURE_TYPE_PSU_STATE: _zes_structure_type_t = 31;
pub const ZES_STRUCTURE_TYPE_BASE_STATE: _zes_structure_type_t = 32;
pub const ZES_STRUCTURE_TYPE_RAS_CONFIG: _zes_structure_type_t = 33;
pub const ZES_STRUCTURE_TYPE_RAS_STATE: _zes_structure_type_t = 34;
pub const ZES_STRUCTURE_TYPE_TEMP_CONFIG: _zes_structure_type_t = 35;
pub const ZES_STRUCTURE_TYPE_PCI_BAR_PROPERTIES_1_2: _zes_structure_type_t = 36;
pub const ZES_STRUCTURE_TYPE_DEVICE_ECC_DESC: _zes_structure_type_t = 37;
pub const ZES_STRUCTURE_TYPE_DEVICE_ECC_PROPERTIES: _zes_structure_type_t = 38;
pub const ZES_STRUCTURE_TYPE_POWER_LIMIT_EXT_DESC: _zes_structure_type_t = 39;
pub const ZES_STRUCTURE_TYPE_POWER_EXT_PROPERTIES: _zes_structure_type_t = 40;
pub const ZES_STRUCTURE_TYPE_OVERCLOCK_PROPERTIES: _zes_structure_type_t = 41;
pub const ZES_STRUCTURE_TYPE_FABRIC_PORT_ERROR_COUNTERS: _zes_structure_type_t = 42;
pub const ZES_STRUCTURE_TYPE_ENGINE_EXT_PROPERTIES: _zes_structure_type_t = 43;
pub const ZES_STRUCTURE_TYPE_RESET_PROPERTIES: _zes_structure_type_t = 44;
pub const ZES_STRUCTURE_TYPE_DEVICE_EXT_PROPERTIES: _zes_structure_type_t = 45;
pub const ZES_STRUCTURE_TYPE_DEVICE_UUID: _zes_structure_type_t = 46;
pub const ZES_STRUCTURE_TYPE_POWER_DOMAIN_EXP_PROPERTIES: _zes_structure_type_t = 131073;
pub const ZES_STRUCTURE_TYPE_MEM_BANDWIDTH_COUNTER_BITS_EXP_PROPERTIES: _zes_structure_type_t =
    131074;
pub const ZES_STRUCTURE_TYPE_MEMORY_PAGE_OFFLINE_STATE_EXP: _zes_structure_type_t = 131075;
pub const ZES_STRUCTURE_TYPE_SUBDEVICE_EXP_PROPERTIES: _zes_structure_type_t = 131076;
pub const ZES_STRUCTURE_TYPE_VF_EXP_PROPERTIES: _zes_structure_type_t = 131077;
pub const ZES_STRUCTURE_TYPE_VF_UTIL_MEM_EXP: _zes_structure_type_t = 131078;
pub const ZES_STRUCTURE_TYPE_VF_UTIL_ENGINE_EXP: _zes_structure_type_t = 131079;
pub const ZES_STRUCTURE_TYPE_VF_EXP_CAPABILITIES: _zes_structure_type_t = 131080;
pub const ZES_STRUCTURE_TYPE_VF_UTIL_MEM_EXP2: _zes_structure_type_t = 131081;
pub const ZES_STRUCTURE_TYPE_VF_UTIL_ENGINE_EXP2: _zes_structure_type_t = 131088;
pub const ZES_STRUCTURE_TYPE_VF_EXP2_CAPABILITIES: _zes_structure_type_t = 131089;
pub const ZES_STRUCTURE_TYPE_DEVICE_ECC_DEFAULT_PROPERTIES_EXT: _zes_structure_type_t = 131090;
pub const ZES_STRUCTURE_TYPE_PCI_LINK_SPEED_DOWNGRADE_EXT_STATE: _zes_structure_type_t = 131091;
pub const ZES_STRUCTURE_TYPE_PCI_LINK_SPEED_DOWNGRADE_EXT_PROPERTIES: _zes_structure_type_t =
    131092;
pub const ZES_STRUCTURE_TYPE_FORCE_UINT32: _zes_structure_type_t = 2147483647;
pub type _zes_structure_type_t = ::std::os::raw::c_uint;
pub use self::_zes_structure_type_t as zes_structure_type_t;
pub type zes_device_properties_t = _zes_device_properties_t;
pub type zes_pci_address_t = _zes_pci_address_t;
pub type zes_pci_speed_t = _zes_pci_speed_t;
pub type zes_pci_properties_t = _zes_pci_properties_t;
pub type zes_engine_properties_t = _zes_engine_properties_t;
pub type zes_engine_stats_t = _zes_engine_stats_t;
pub type zes_freq_properties_t = _zes_freq_properties_t;
pub type zes_freq_state_t = _zes_freq_state_t;
pub type zes_power_properties_t = _zes_power_properties_t;
pub type zes_power_energy_counter_t = _zes_power_energy_counter_t;
pub type zes_temp_properties_t = _zes_temp_properties_t;
pub type zes_power_limit_ext_desc_t = _zes_power_limit_ext_desc_t;
pub type zes_power_ext_properties_t = _zes_power_ext_properties_t;
pub type zes_init_flags_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _zes_device_properties_t {
    pub stype: zes_structure_type_t,
    pub pNext: *mut ::std::os::raw::c_void,
    pub core: ze_device_properties_t,
    pub numSubdevices: u32,
    pub serialNumber: [::std::os::raw::c_char; 64usize],
    pub boardNumber: [::std::os::raw::c_char; 64usize],
    pub brandName: [::std::os::raw::c_char; 64usize],
    pub modelName: [::std::os::raw::c_char; 64usize],
    pub vendorName: [::std::os::raw::c_char; 64usize],
    pub driverVersion: [::std::os::raw::c_char; 64usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _zes_device_properties_t"]
        [::std::mem::size_of::<_zes_device_properties_t>() - 776usize];
    ["Alignment of _zes_device_properties_t"]
        [::std::mem::align_of::<_zes_device_properties_t>() - 8usize];
    ["Offset of field: _zes_device_properties_t::stype"]
        [::std::mem::offset_of!(_zes_device_properties_t, stype) - 0usize];
    ["Offset of field: _zes_device_properties_t::pNext"]
        [::std::mem::offset_of!(_zes_device_properties_t, pNext) - 8usize];
    ["Offset of field: _zes_device_properties_t::core"]
        [::std::mem::offset_of!(_zes_device_properties_t, core) - 16usize];
    ["Offset of field: _zes_device_properties_t::numSubdevices"]
        [::std::mem::offset_of!(_zes_device_properties_t, numSubdevices) - 384usize];
    ["Offset of field: _zes_device_properties_t::serialNumber"]
        [::std::mem::offset_of!(_zes_device_properties_t, serialNumber) - 388usize];
    ["Offset of field: _zes_device_properties_t::boardNumber"]
        [::std::mem::offset_of!(_zes_device_properties_t, boardNumber) - 452usize];
    ["Offset of field: _zes_device_properties_t::brandName"]
        [::std::mem::offset_of!(_zes_device_properties_t, brandName) - 516usize];
    ["Offset of field: _zes_device_properties_t::modelName"]
        [::std::mem::offset_of!(_zes_device_properties_t, modelName) - 580usize];
    ["Offset of field: _zes_device_properties_t::vendorName"]
        [::std::mem::offset_of!(_zes_device_properties_t, vendorName) - 644usize];
    ["Offset of field: _zes_device_properties_t::driverVersion"]
        [::std::mem::offset_of!(_zes_device_properties_t, driverVersion) - 708usize];
};
impl Default for _zes_device_properties_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _zes_pci_address_t {
    pub domain: u32,
    pub bus: u32,
    pub device: u32,
    pub function: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _zes_pci_address_t"][::std::mem::size_of::<_zes_pci_address_t>() - 16usize];
    ["Alignment of _zes_pci_address_t"][::std::mem::align_of::<_zes_pci_address_t>() - 4usize];
    ["Offset of field: _zes_pci_address_t::domain"]
        [::std::mem::offset_of!(_zes_pci_address_t, domain) - 0usize];
    ["Offset of field: _zes_pci_address_t::bus"]
        [::std::mem::offset_of!(_zes_pci_address_t, bus) - 4usize];
    ["Offset of field: _zes_pci_address_t::device"]
        [::std::mem::offset_of!(_zes_pci_address_t, device) - 8usize];
    ["Offset of field: _zes_pci_address_t::function"]
        [::std::mem::offset_of!(_zes_pci_address_t, function) - 12usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _zes_pci_speed_t {
    pub gen_: i32,
    pub width: i32,
    pub maxBandwidth: i64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _zes_pci_speed_t"][::std::mem::size_of::<_zes_pci_speed_t>() - 16usize];
    ["Alignment of _zes_pci_speed_t"][::std::mem::align_of::<_zes_pci_speed_t>() - 8usize];
    ["Offset of field: _zes_pci_speed_t::gen_"]
        [::std::mem::offset_of!(_zes_pci_speed_t, gen_) - 0usize];
    ["Offset of field: _zes_pci_speed_t::width"]
        [::std::mem::offset_of!(_zes_pci_speed_t, width) - 4usize];
    ["Offset of field: _zes_pci_speed_t::maxBandwidth"]
        [::std::mem::offset_of!(_zes_pci_speed_t, maxBandwidth) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _zes_pci_properties_t {
    pub stype: zes_structure_type_t,
    pub pNext: *mut ::std::os::raw::c_void,
    pub address: zes_pci_address_t,
    pub maxSpeed: zes_pci_speed_t,
    pub haveBandwidthCounters: ze_bool_t,
    pub havePacketCounters: ze_bool_t,
    pub haveReplayCounters: ze_bool_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _zes_pci_properties_t"][::std::mem::size_of::<_zes_pci_properties_t>() - 56usize];
    ["Alignment of _zes_pci_properties_t"]
        [::std::mem::align_of::<_zes_pci_properties_t>() - 8usize];
    ["Offset of field: _zes_pci_properties_t::stype"]
        [::std::mem::offset_of!(_zes_pci_properties_t, stype) - 0usize];
    ["Offset of field: _zes_pci_properties_t::pNext"]
        [::std::mem::offset_of!(_zes_pci_properties_t, pNext) - 8usize];
    ["Offset of field: _zes_pci_properties_t::address"]
        [::std::mem::offset_of!(_zes_pci_properties_t, address) - 16usize];
    ["Offset of field: _zes_pci_properties_t::maxSpeed"]
        [::std::mem::offset_of!(_zes_pci_properties_t, maxSpeed) - 32usize];
    ["Offset of field: _zes_pci_properties_t::haveBandwidthCounters"]
        [::std::mem::offset_of!(_zes_pci_properties_t, haveBandwidthCounters) - 48usize];
    ["Offset of field: _zes_pci_properties_t::havePacketCounters"]
        [::std::mem::offset_of!(_zes_pci_properties_t, havePacketCounters) - 49usize];
    ["Offset of field: _zes_pci_properties_t::haveReplayCounters"]
        [::std::mem::offset_of!(_zes_pci_properties_t, haveReplayCounters) - 50usize];
};
impl Default for _zes_pci_properties_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const ZES_ENGINE_GROUP_ALL: _zes_engine_group_t = 0;
pub const ZES_ENGINE_GROUP_COMPUTE_ALL: _zes_engine_group_t = 1;
pub const ZES_ENGINE_GROUP_MEDIA_ALL: _zes_engine_group_t = 2;
pub const ZES_ENGINE_GROUP_COPY_ALL: _zes_engine_group_t = 3;
pub const ZES_ENGINE_GROUP_COMPUTE_SINGLE: _zes_engine_group_t = 4;
pub const ZES_ENGINE_GROUP_RENDER_SINGLE: _zes_engine_group_t = 5;
pub const ZES_ENGINE_GROUP_MEDIA_DECODE_SINGLE: _zes_engine_group_t = 6;
pub const ZES_ENGINE_GROUP_MEDIA_ENCODE_SINGLE: _zes_engine_group_t = 7;
pub const ZES_ENGINE_GROUP_COPY_SINGLE: _zes_engine_group_t = 8;
pub const ZES_ENGINE_GROUP_MEDIA_ENHANCEMENT_SINGLE: _zes_engine_group_t = 9;
pub const ZES_ENGINE_GROUP_3D_SINGLE: _zes_engine_group_t = 10;
pub const ZES_ENGINE_GROUP_3D_RENDER_COMPUTE_ALL: _zes_engine_group_t = 11;
pub const ZES_ENGINE_GROUP_RENDER_ALL: _zes_engine_group_t = 12;
pub const ZES_ENGINE_GROUP_3D_ALL: _zes_engine_group_t = 13;
pub const ZES_ENGINE_GROUP_MEDIA_CODEC_SINGLE: _zes_engine_group_t = 14;
pub const ZES_ENGINE_GROUP_FORCE_UINT32: _zes_engine_group_t = 2147483647;
pub type _zes_engine_group_t = ::std::os::raw::c_uint;
pub use self::_zes_engine_group_t as zes_engine_group_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _zes_engine_properties_t {
    pub stype: zes_structure_type_t,
    pub pNext: *mut ::std::os::raw::c_void,
    pub type_: zes_engine_group_t,
    pub onSubdevice: ze_bool_t,
    pub subdeviceId: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _zes_engine_properties_t"]
        [::std::mem::size_of::<_zes_engine_properties_t>() - 32usize];
    ["Alignment of _zes_engine_properties_t"]
        [::std::mem::align_of::<_zes_engine_properties_t>() - 8usize];
    ["Offset of field: _zes_engine_properties_t::stype"]
        [::std::mem::offset_of!(_zes_engine_properties_t, stype) - 0usize];
    ["Offset of field: _zes_engine_properties_t::pNext"]
        [::std::mem::offset_of!(_zes_engine_properties_t, pNext) - 8usize];
    ["Offset of field: _zes_engine_properties_t::type_"]
        [::std::mem::offset_of!(_zes_engine_properties_t, type_) - 16usize];
    ["Offset of field: _zes_engine_properties_t::onSubdevice"]
        [::std::mem::offset_of!(_zes_engine_properties_t, onSubdevice) - 20usize];
    ["Offset of field: _zes_engine_properties_t::subdeviceId"]
        [::std::mem::offset_of!(_zes_engine_properties_t, subdeviceId) - 24usize];
};
impl Default for _zes_engine_properties_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _zes_engine_stats_t {
    pub activeTime: u64,
    pub timestamp: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _zes_engine_stats_t"][::std::mem::size_of::<_zes_engine_stats_t>() - 16usize];
    ["Alignment of _zes_engine_stats_t"][::std::mem::align_of::<_zes_engine_stats_t>() - 8usize];
    ["Offset of field: _zes_engine_stats_t::activeTime"]
        [::std::mem::offset_of!(_zes_engine_stats_t, activeTime) - 0usize];
    ["Offset of field: _zes_engine_stats_t::timestamp"]
        [::std::mem::offset_of!(_zes_engine_stats_t, timestamp) - 8usize];
};
pub const ZES_FREQ_DOMAIN_GPU: _zes_freq_domain_t = 0;
pub const ZES_FREQ_DOMAIN_MEMORY: _zes_freq_domain_t = 1;
pub const ZES_FREQ_DOMAIN_MEDIA: _zes_freq_domain_t = 2;
pub const ZES_FREQ_DOMAIN_FORCE_UINT32: _zes_freq_domain_t = 2147483647;
pub type _zes_freq_domain_t = ::std::os::raw::c_uint;
pub use self::_zes_freq_domain_t as zes_freq_domain_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _zes_freq_properties_t {
    pub stype: zes_structure_type_t,
    pub pNext: *mut ::std::os::raw::c_void,
    pub type_: zes_freq_domain_t,
    pub onSubdevice: ze_bool_t,
    pub subdeviceId: u32,
    pub canControl: ze_bool_t,
    pub isThrottleEventSupported: ze_bool_t,
    pub min: f64,
    pub max: f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _zes_freq_properties_t"][::std::mem::size_of::<_zes_freq_properties_t>() - 48usize];
    ["Alignment of _zes_freq_properties_t"]
        [::std::mem::align_of::<_zes_freq_properties_t>() - 8usize];
    ["Offset of field: _zes_freq_properties_t::stype"]
        [::std::mem::offset_of!(_zes_freq_properties_t, stype) - 0usize];
    ["Offset of field: _zes_freq_properties_t::pNext"]
        [::std::mem::offset_of!(_zes_freq_properties_t, pNext) - 8usize];
    ["Offset of field: _zes_freq_properties_t::type_"]
        [::std::mem::offset_of!(_zes_freq_properties_t, type_) - 16usize];
    ["Offset of field: _zes_freq_properties_t::onSubdevice"]
        [::std::mem::offset_of!(_zes_freq_properties_t, onSubdevice) - 20usize];
    ["Offset of field: _zes_freq_properties_t::subdeviceId"]
        [::std::mem::offset_of!(_zes_freq_properties_t, subdeviceId) - 24usize];
    ["Offset of field: _zes_freq_properties_t::canControl"]
        [::std::mem::offset_of!(_zes_freq_properties_t, canControl) - 28usize];
    ["Offset of field: _zes_freq_properties_t::isThrottleEventSupported"]
        [::std::mem::offset_of!(_zes_freq_properties_t, isThrottleEventSupported) - 29usize];
    ["Offset of field: _zes_freq_properties_t::min"]
        [::std::mem::offset_of!(_zes_freq_properties_t, min) - 32usize];
    ["Offset of field: _zes_freq_properties_t::max"]
        [::std::mem::offset_of!(_zes_freq_properties_t, max) - 40usize];
};
impl Default for _zes_freq_properties_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type zes_freq_throttle_reason_flags_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _zes_freq_state_t {
    pub stype: zes_structure_type_t,
    pub pNext: *const ::std::os::raw::c_void,
    pub currentVoltage: f64,
    pub request: f64,
    pub tdp: f64,
    pub efficient: f64,
    pub actual: f64,
    pub throttleReasons: zes_freq_throttle_reason_flags_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _zes_freq_state_t"][::std::mem::size_of::<_zes_freq_state_t>() - 64usize];
    ["Alignment of _zes_freq_state_t"][::std::mem::align_of::<_zes_freq_state_t>() - 8usize];
    ["Offset of field: _zes_freq_state_t::stype"]
        [::std::mem::offset_of!(_zes_freq_state_t, stype) - 0usize];
    ["Offset of field: _zes_freq_state_t::pNext"]
        [::std::mem::offset_of!(_zes_freq_state_t, pNext) - 8usize];
    ["Offset of field: _zes_freq_state_t::currentVoltage"]
        [::std::mem::offset_of!(_zes_freq_state_t, currentVoltage) - 16usize];
    ["Offset of field: _zes_freq_state_t::request"]
        [::std::mem::offset_of!(_zes_freq_state_t, request) - 24usize];
    ["Offset of field: _zes_freq_state_t::tdp"]
        [::std::mem::offset_of!(_zes_freq_state_t, tdp) - 32usize];
    ["Offset of field: _zes_freq_state_t::efficient"]
        [::std::mem::offset_of!(_zes_freq_state_t, efficient) - 40usize];
    ["Offset of field: _zes_freq_state_t::actual"]
        [::std::mem::offset_of!(_zes_freq_state_t, actual) - 48usize];
    ["Offset of field: _zes_freq_state_t::throttleReasons"]
        [::std::mem::offset_of!(_zes_freq_state_t, throttleReasons) - 56usize];
};
impl Default for _zes_freq_state_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const ZES_POWER_DOMAIN_UNKNOWN: _zes_power_domain_t = 0;
pub const ZES_POWER_DOMAIN_CARD: _zes_power_domain_t = 1;
pub const ZES_POWER_DOMAIN_PACKAGE: _zes_power_domain_t = 2;
pub const ZES_POWER_DOMAIN_STACK: _zes_power_domain_t = 3;
pub const ZES_POWER_DOMAIN_MEMORY: _zes_power_domain_t = 4;
pub const ZES_POWER_DOMAIN_GPU: _zes_power_domain_t = 5;
pub const ZES_POWER_DOMAIN_FORCE_UINT32: _zes_power_domain_t = 2147483647;
pub type _zes_power_domain_t = ::std::os::raw::c_uint;
pub use self::_zes_power_domain_t as zes_power_domain_t;
pub const ZES_POWER_LEVEL_UNKNOWN: _zes_power_level_t = 0;
pub const ZES_POWER_LEVEL_SUSTAINED: _zes_power_level_t = 1;
pub const ZES_POWER_LEVEL_BURST: _zes_power_level_t = 2;
pub const ZES_POWER_LEVEL_PEAK: _zes_power_level_t = 3;
pub const ZES_POWER_LEVEL_INSTANTANEOUS: _zes_power_level_t = 4;
pub const ZES_POWER_LEVEL_FORCE_UINT32: _zes_power_level_t = 2147483647;
pub type _zes_power_level_t = ::std::os::raw::c_uint;
pub use self::_zes_power_level_t as zes_power_level_t;
pub const ZES_POWER_SOURCE_ANY: _zes_power_source_t = 0;
pub const ZES_POWER_SOURCE_MAINS: _zes_power_source_t = 1;
pub const ZES_POWER_SOURCE_BATTERY: _zes_power_source_t = 2;
pub const ZES_POWER_SOURCE_FORCE_UINT32: _zes_power_source_t = 2147483647;
pub type _zes_power_source_t = ::std::os::raw::c_uint;
pub use self::_zes_power_source_t as zes_power_source_t;
pub const ZES_LIMIT_UNIT_UNKNOWN: _zes_limit_unit_t = 0;
pub const ZES_LIMIT_UNIT_CURRENT: _zes_limit_unit_t = 1;
pub const ZES_LIMIT_UNIT_POWER: _zes_limit_unit_t = 2;
pub const ZES_LIMIT_UNIT_FORCE_UINT32: _zes_limit_unit_t = 2147483647;
pub type _zes_limit_unit_t = ::std::os::raw::c_uint;
pub use self::_zes_limit_unit_t as zes_limit_unit_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _zes_power_properties_t {
    pub stype: zes_structure_type_t,
    pub pNext: *mut ::std::os::raw::c_void,
    pub onSubdevice: ze_bool_t,
    pub subdeviceId: u32,
    pub canControl: ze_bool_t,
    pub isEnergyThresholdSupported: ze_bool_t,
    pub defaultLimit: i32,
    pub minLimit: i32,
    pub maxLimit: i32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _zes_power_properties_t"][::std::mem::size_of::<_zes_power_properties_t>() - 40usize];
    ["Alignment of _zes_power_properties_t"]
        [::std::mem::align_of::<_zes_power_properties_t>() - 8usize];
    ["Offset of field: _zes_power_properties_t::stype"]
        [::std::mem::offset_of!(_zes_power_properties_t, stype) - 0usize];
    ["Offset of field: _zes_power_properties_t::pNext"]
        [::std::mem::offset_of!(_zes_power_properties_t, pNext) - 8usize];
    ["Offset of field: _zes_power_properties_t::onSubdevice"]
        [::std::mem::offset_of!(_zes_power_properties_t, onSubdevice) - 16usize];
    ["Offset of field: _zes_power_properties_t::subdeviceId"]
        [::std::mem::offset_of!(_zes_power_properties_t, subdeviceId) - 20usize];
    ["Offset of field: _zes_power_properties_t::canControl"]
        [::std::mem::offset_of!(_zes_power_properties_t, canControl) - 24usize];
    ["Offset of field: _zes_power_properties_t::isEnergyThresholdSupported"]
        [::std::mem::offset_of!(_zes_power_properties_t, isEnergyThresholdSupported) - 25usize];
    ["Offset of field: _zes_power_properties_t::defaultLimit"]
        [::std::mem::offset_of!(_zes_power_properties_t, defaultLimit) - 28usize];
    ["Offset of field: _zes_power_properties_t::minLimit"]
        [::std::mem::offset_of!(_zes_power_properties_t, minLimit) - 32usize];
    ["Offset of field: _zes_power_properties_t::maxLimit"]
        [::std::mem::offset_of!(_zes_power_properties_t, maxLimit) - 36usize];
};
impl Default for _zes_power_properties_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _zes_power_energy_counter_t {
    pub energy: u64,
    pub timestamp: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _zes_power_energy_counter_t"]
        [::std::mem::size_of::<_zes_power_energy_counter_t>() - 16usize];
    ["Alignment of _zes_power_energy_counter_t"]
        [::std::mem::align_of::<_zes_power_energy_counter_t>() - 8usize];
    ["Offset of field: _zes_power_energy_counter_t::energy"]
        [::std::mem::offset_of!(_zes_power_energy_counter_t, energy) - 0usize];
    ["Offset of field: _zes_power_energy_counter_t::timestamp"]
        [::std::mem::offset_of!(_zes_power_energy_counter_t, timestamp) - 8usize];
};
pub const ZES_TEMP_SENSORS_GLOBAL: _zes_temp_sensors_t = 0;
pub const ZES_TEMP_SENSORS_GPU: _zes_temp_sensors_t = 1;
pub const ZES_TEMP_SENSORS_MEMORY: _zes_temp_sensors_t = 2;
pub const ZES_TEMP_SENSORS_GLOBAL_MIN: _zes_temp_sensors_t = 3;
pub const ZES_TEMP_SENSORS_GPU_MIN: _zes_temp_sensors_t = 4;
pub const ZES_TEMP_SENSORS_MEMORY_MIN: _zes_temp_sensors_t = 5;
pub const ZES_TEMP_SENSORS_GPU_BOARD: _zes_temp_sensors_t = 6;
pub const ZES_TEMP_SENSORS_GPU_BOARD_MIN: _zes_temp_sensors_t = 7;
pub const ZES_TEMP_SENSORS_VOLTAGE_REGULATOR: _zes_temp_sensors_t = 8;
pub const ZES_TEMP_SENSORS_FORCE_UINT32: _zes_temp_sensors_t = 2147483647;
pub type _zes_temp_sensors_t = ::std::os::raw::c_uint;
pub use self::_zes_temp_sensors_t as zes_temp_sensors_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _zes_temp_properties_t {
    pub stype: zes_structure_type_t,
    pub pNext: *mut ::std::os::raw::c_void,
    pub type_: zes_temp_sensors_t,
    pub onSubdevice: ze_bool_t,
    pub subdeviceId: u32,
    pub maxTemperature: f64,
    pub isCriticalTempSupported: ze_bool_t,
    pub isThreshold1Supported: ze_bool_t,
    pub isThreshold2Supported: ze_bool_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _zes_temp_properties_t"][::std::mem::size_of::<_zes_temp_properties_t>() - 48usize];
    ["Alignment of _zes_temp_properties_t"]
        [::std::mem::align_of::<_zes_temp_properties_t>() - 8usize];
    ["Offset of field: _zes_temp_properties_t::stype"]
        [::std::mem::offset_of!(_zes_temp_properties_t, stype) - 0usize];
    ["Offset of field: _zes_temp_properties_t::pNext"]
        [::std::mem::offset_of!(_zes_temp_properties_t, pNext) - 8usize];
    ["Offset of field: _zes_temp_properties_t::type_"]
        [::std::mem::offset_of!(_zes_temp_properties_t, type_) - 16usize];
    ["Offset of field: _zes_temp_properties_t::onSubdevice"]
        [::std::mem::offset_of!(_zes_temp_properties_t, onSubdevice) - 20usize];
    ["Offset of field: _zes_temp_properties_t::subdeviceId"]
        [::std::mem::offset_of!(_zes_temp_properties_t, subdeviceId) - 24usize];
    ["Offset of field: _zes_temp_properties_t::maxTemperature"]
        [::std::mem::offset_of!(_zes_temp_properties_t, maxTemperature) - 32usize];
    ["Offset of field: _zes_temp_properties_t::isCriticalTempSupported"]
        [::std::mem::offset_of!(_zes_temp_properties_t, isCriticalTempSupported) - 40usize];
    ["Offset of field: _zes_temp_properties_t::isThreshold1Supported"]
        [::std::mem::offset_of!(_zes_temp_properties_t, isThreshold1Supported) - 41usize];
    ["Offset of field: _zes_temp_properties_t::isThreshold2Supported"]
        [::std::mem::offset_of!(_zes_temp_properties_t, isThreshold2Supported) - 42usize];
};
impl Default for _zes_temp_properties_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _zes_power_limit_ext_desc_t {
    pub stype: zes_structure_type_t,
    pub pNext: *const ::std::os::raw::c_void,
    pub level: zes_power_level_t,
    pub source: zes_power_source_t,
    pub limitUnit: zes_limit_unit_t,
    pub enabledStateLocked: ze_bool_t,
    pub enabled: ze_bool_t,
    pub intervalValueLocked: ze_bool_t,
    pub interval: i32,
    pub limitValueLocked: ze_bool_t,
    pub limit: i32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _zes_power_limit_ext_desc_t"]
        [::std::mem::size_of::<_zes_power_limit_ext_desc_t>() - 48usize];
    ["Alignment of _zes_power_limit_ext_desc_t"]
        [::std::mem::align_of::<_zes_power_limit_ext_desc_t>() - 8usize];
    ["Offset of field: _zes_power_limit_ext_desc_t::stype"]
        [::std::mem::offset_of!(_zes_power_limit_ext_desc_t, stype) - 0usize];
    ["Offset of field: _zes_power_limit_ext_desc_t::pNext"]
        [::std::mem::offset_of!(_zes_power_limit_ext_desc_t, pNext) - 8usize];
    ["Offset of field: _zes_power_limit_ext_desc_t::level"]
        [::std::mem::offset_of!(_zes_power_limit_ext_desc_t, level) - 16usize];
    ["Offset of field: _zes_power_limit_ext_desc_t::source"]
        [::std::mem::offset_of!(_zes_power_limit_ext_desc_t, source) - 20usize];
    ["Offset of field: _zes_power_limit_ext_desc_t::limitUnit"]
        [::std::mem::offset_of!(_zes_power_limit_ext_desc_t, limitUnit) - 24usize];
    ["Offset of field: _zes_power_limit_ext_desc_t::enabledStateLocked"]
        [::std::mem::offset_of!(_zes_power_limit_ext_desc_t, enabledStateLocked) - 28usize];
    ["Offset of field: _zes_power_limit_ext_desc_t::enabled"]
        [::std::mem::offset_of!(_zes_power_limit_ext_desc_t, enabled) - 29usize];
    ["Offset of field: _zes_power_limit_ext_desc_t::intervalValueLocked"]
        [::std::mem::offset_of!(_zes_power_limit_ext_desc_t, intervalValueLocked) - 30usize];
    ["Offset of field: _zes_power_limit_ext_desc_t::interval"]
        [::std::mem::offset_of!(_zes_power_limit_ext_desc_t, interval) - 32usize];
    ["Offset of field: _zes_power_limit_ext_desc_t::limitValueLocked"]
        [::std::mem::offset_of!(_zes_power_limit_ext_desc_t, limitValueLocked) - 36usize];
    ["Offset of field: _zes_power_limit_ext_desc_t::limit"]
        [::std::mem::offset_of!(_zes_power_limit_ext_desc_t, limit) - 40usize];
};
impl Default for _zes_power_limit_ext_desc_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _zes_power_ext_properties_t {
    pub stype: zes_structure_type_t,
    pub pNext: *mut ::std::os::raw::c_void,
    pub domain: zes_power_domain_t,
    pub defaultLimit: *mut zes_power_limit_ext_desc_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _zes_power_ext_properties_t"]
        [::std::mem::size_of::<_zes_power_ext_properties_t>() - 32usize];
    ["Alignment of _zes_power_ext_properties_t"]
        [::std::mem::align_of::<_zes_power_ext_properties_t>() - 8usize];
    ["Offset of field: _zes_power_ext_properties_t::stype"]
        [::std::mem::offset_of!(_zes_power_ext_properties_t, stype) - 0usize];
    ["Offset of field: _zes_power_ext_properties_t::pNext"]
        [::std::mem::offset_of!(_zes_power_ext_properties_t, pNext) - 8usize];
    ["Offset of field: _zes_power_ext_properties_t::domain"]
        [::std::mem::offset_of!(_zes_power_ext_properties_t, domain) - 16usize];
    ["Offset of field: _zes_power_ext_properties_t::defaultLimit"]
        [::std::mem::offset_of!(_zes_power_ext_properties_t, defaultLimit) - 24usize];
};
impl Default for _zes_power_ext_properties_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
